# Generated by Django 5.0.4 on 2024-04-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('advert', models.CharField(max_length=50, verbose_name='Advertisement')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('facebook', models.CharField(max_length=255, verbose_name='Facebook')),
                ('instagram', models.CharField(max_length=255, verbose_name='Instagram')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('address_url', models.CharField(max_length=255, verbose_name='Address URL')),
            ],
            options={
                'verbose_name': 'BaseSetting',
                'verbose_name_plural': 'BaseSettings',
            },
        ),
    ]
